<?xml version="1.0" encoding="utf-8"?><Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Certes" Version="3.0.4" />
    <PackageVersion Include="KubernetesClient" Version="19.0.2" />
    <PackageVersion Include="LagoVista.AspNetCore.Identity" Version="7.0.12" />
    <PackageVersion Include="LagoVista.CloudStorage" Version="7.0.73-wst.build-dynamics-platf" />
    <PackageVersion Include="LagoVista.Core.Configuration" Version="7.0.14" />
    <PackageVersion Include="LagoVista.Core.Rcg.Client" Version="7.0.14" />
    <PackageVersion Include="LagoVista.UserAdmin" Version="7.0.12" />
    <PackageVersion Include="Microsoft.AspNetCore" Version="2.3.9" />
    <PackageVersion Include="Portable.BouncyCastle" Version="1.9.0" />
    <PackageVersion Include="prometheus-net.AspNetCore" Version="8.2.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="MSTest.TestAdapter" Version="3.10.4" />
    <PackageVersion Include="MSTest.TestFramework" Version="3.10.4" />
  </ItemGroup>
</Project>
