<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <VersionPrefix>1.2.164</VersionPrefix>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyVersion>1.2.164.0</AssemblyVersion>
    <FileVersion>1.2.164.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LagoVista.CloudStorage" />
    <PackageReference Include="Certes" />
    <PackageReference Include="Microsoft.AspNetCore" />
    <PackageReference Include="Portable.BouncyCastle" />
  </ItemGroup>
</Project>
